apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-config
 namespace: taskflow
data:
 prometheus.yml: |
   global:
     scrape_interval: 15s
   scrape_configs:
     - job_name: "taskflow"
       static_configs:
         - targets: ["taskflow-service:5000"]
