{{- if .Values.prometheus.kubeStateMetrics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.kubeStateMetrics.serviceName }}
  labels:
    {{- include "taskflow-chart.labels" . | nindent 4 }}
{{- end }}
